apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app: profile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: nginx:1.14.2
        ports:
        - containerPort: 80
